version: '3.8'

services:
  my_database:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - my_db_data:/var/lib/postgresql/data
    command: ["docker-entrypoint.sh", "postgres", "-c", "max_connections=100"]

  my_database_users:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database_users5
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 123
    ports:
      - "7777:5432"
    volumes:
      - my_db_data_users:/var/lib/postgresql/data

  my_login_app:
    image: python:3.8
    ports:
      - "8503:8503"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      /bin/bash -c "
      pip install streamlit psycopg2-binary &&
      streamlit run login.py --server.port 8503
      "

  my_spark:
    image: jupyter/pyspark-notebook:latest
    user: root
    environment:
      - SPARK_HOME=/usr/local/spark
      - PYSPARK_SUBMIT_ARGS=--driver-class-path /app/postgresql-42.7.2.jar pyspark-shell
    ports:
      - "8888:8888" # Port dla Jupyter
      - "8501:8501" # Dodatkowy port dla Streamlit
    volumes:
      - ./postgresql-42.7.2.jar:/app/postgresql-42.7.2.jar
      - .:/home/jovyan  # Mapowanie całego aktualnego katalogu do kontenera
      - ./init.sql:/app/init.sql
    command: /bin/bash -c "pip install pyspark streamlit geopy streamlit_folium && streamlit run frontend.py"



volumes:
  my_db_data_users:
  my_db_data:
